### PR TITLE
Order Tracking Component

### PR DESCRIPTION
**Pull request by VictoriaAjala**
This fixes issue #90 

Screenshot from 2023-02-06 17-37-27

### CODE REVIEW

**Comment by ifedayoagboola** [comment]
The "track-my-order" link on the navbar should have the path to your component, not order history as it is ATM.

**Comment by VictoriaAjala** [comment]
> The "track-my-order" link on the navbar should have the path to your component, not order history as it is ATM.

Done!

**Review by ifedayoagboola — COMMENTED** [review]
Merged but not responsive

**Comment by VictoriaAjala** [comment]
> Merged but not responsive

Noted!

**Pull request merged**
